MyMusicApp/albums/urls.py
from django.urls import path, include
from .views import AlbumCreateView, AlbumDetailsView, AlbumEditView, AlbumDeleteView

urlpatterns = [
    path("add/", AlbumCreateView.as_view(), name="album-create"),
    path("<int:pk>/", include([
        path("details/", AlbumDetailsView.as_view(), name="album-details"),
        path("edit/", AlbumEditView.as_view(), name="album-edit"),
        path("delete/", AlbumDeleteView.as_view(), name="album-delete")
    ]))
]

MyMusicApp/profiles/urls.py
from django.urls import include, path

from MyMusicApp.profiles.views import ProfileDetailView, ProfileDeleteView

urlpatterns = [
    path("details/", ProfileDetailView.as_view(), name="profile-details"),
    path("delete/", ProfileDeleteView.as_view(), name="profile-delete")
]

MyMusicApp/songs/urls.py
from django.urls import path, include
from .views import SongCreateView, SongServeView, SongPlayView

urlpatterns = [
    path('create/', SongCreateView.as_view(), name='create-song'),
    path("<int:pk>/", include([
        path("serve/", SongServeView.as_view(), name='serve-song'),
    path("play/", SongPlayView.as_view(), name='play-song'),
    ]))
]

MyMusicApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("MyMusicApp.web.urls")),
    path("album/", include("MyMusicApp.albums.urls")),
    path("profile/", include("MyMusicApp.profiles.urls")),
    path("song/", include("MyMusicApp.songs.urls"))
]

MyMusicApp/web/urls.py
from django.urls import path

from MyMusicApp.web.views import IndexView, ProfileCreateView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create-profile/', ProfileCreateView.as_view(), name='profile-create'),
]

MyMusicApp/albums/models.py
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from MyMusicApp.albums.choices import MusicGenre


class Album(models.Model):
    MAX_ALBUM_NAME_LENGTH = 30
    MAX_ARTIST_LENGTH = 30
    MAX_GENRE_LENGTH = 30

    MIN_PRICE = 0.0

    album_name = models.CharField(
        max_length=MAX_ALBUM_NAME_LENGTH,
        unique=True,
        null=False,
        blank=False,
        verbose_name="Album Name"
    )
    artist = models.CharField(
        max_length=MAX_ARTIST_LENGTH,
        null=False,
        blank=False,
        verbose_name="Artist"

    )

    genre = models.CharField(
        max_length=MAX_GENRE_LENGTH,
        choices=MusicGenre.choices
    )

    description = models. TextField(
        null=True,
        blank=True
    )

    image_url = models.URLField(
        null=False,
        blank=False
    )

    price = models.FloatField(
        validators=[
            MinValueValidator(MIN_PRICE)
        ],
        null=False,
        blank=False
    )

    owner = models.ForeignKey(
        "profiles.Profile",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.album_name

MyMusicApp/profiles/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from MyMusicApp.profiles.validators import UserNameValidator


class Profile(models.Model):
    MIN_USERNAME_LENGTH = 2
    MAX_USERNAME_LENGTH = 15

    username = models.CharField(
        max_length=MAX_USERNAME_LENGTH,
        validators=[
            MinLengthValidator(MIN_USERNAME_LENGTH),
            UserNameValidator(),
        ],
        null=False,
        blank=False
    )

    email = models.EmailField(
        null=False,
        blank=False
    )
    age = models.PositiveIntegerField(
        null=True,
        blank=True
    )

MyMusicApp/songs/models.py
from django.db import models


class Song(models.Model):
    MAX_SONG_NAME_LENGTH = 140

    song_name = models.CharField(
        max_length=MAX_SONG_NAME_LENGTH,
        null=False,
        blank=False
    )

    music_file_data = models.BinaryField(
        null=False,
        blank=False
    )

    album = models.ForeignKey(
        'albums.Album',
        on_delete=models.CASCADE,
        related_name='songs'
    )

    def __str__(self):
        return self.song_name

MyMusicApp/web/models.py
from django.db import models

# Create your models here.

MyMusicApp/albums/views.py
from django.forms import modelform_factory
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from MyMusicApp.albums.mixins import AlbumFormPlaceholderMixin
from MyMusicApp.albums.models import Album
from MyMusicApp.utils.mixins import ReadOnlyFormMixin
from MyMusicApp.utils.profile_helpers import get_profile


class AlbumCreateView(AlbumFormPlaceholderMixin, CreateView):
    model = Album
    fields = ["album_name", "artist", "genre", "description", "image_url", "price"]
    template_name = "albums/album-add.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        profile = get_profile()
        form.instance.owner = profile
        return super().form_valid(form)


class AlbumDetailsView(DetailView):
    model = Album
    template_name = "albums/album-details.html"


class AlbumEditView(UpdateView):
    model = Album
    template_name = "albums/album-edit.html"
    fields = ["album_name", "artist", "genre", "description", "image_url", "price"]
    success_url = reverse_lazy("index")


class AlbumDeleteView(ReadOnlyFormMixin, DeleteView):
    model = Album
    template_name = "albums/album-delete.html"
    success_url = reverse_lazy("index")
    form_class = modelform_factory(
        Album,
        fields=("album_name", "artist", "genre", "description", "image_url", "price"),
    )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs

MyMusicApp/profiles/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView

from MyMusicApp.utils.profile_helpers import get_profile


class ProfileDetailView(DetailView):
    template_name = "profiles/profile-details.html"

    def get_object(self, queryset=None):
        return get_profile()


class ProfileDeleteView(DeleteView):
    template_name = "profiles/profile-delete.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return get_profile()

MyMusicApp/songs/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from .models import Song


from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Song


class SongCreateView(CreateView):
    model = Song
    fields = ['song_name', 'album']
    template_name = 'songs/create-song.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        music_file = self.request.FILES.get('music_file')
        form.instance.music_file_data = music_file.read()
        return super().form_valid(form)


class SongServeView(DetailView):
    model = Song

    def render_to_response(self, context, **response_kwargs):
        song = self.get_object()  # Get the song object from the database

        # Serve the binary file as a response
        response = HttpResponse(song.music_file_data, content_type="audio/mpeg")
        response["Content-Disposition"] = f'inline; filename="{song.song_name}"'
        return response


class SongPlayView(DetailView):
    model = Song
    template_name = "songs/music-player.html"
    context_object_name = "song"

    def get_object(self, queryset=None):
        # If you need a custom query, you can define it here
        return super().get_object(queryset)

MyMusicApp/web/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .mixins import ProfileFormPlaceholderMixin
from ..albums.models import Album
from ..profiles.models import Profile
from ..utils.profile_helpers import get_profile


class ProfileCreateView(ProfileFormPlaceholderMixin, CreateView):
    model = Profile
    fields = ['username', 'email', 'age']
    template_name = "web/home-no-profile.html"
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class IndexView(TemplateView):
    template_name = 'web/home-with-profile.html'

    def get(self, request, *args, **kwargs):
        profile = get_profile()
        if profile is None:
            return redirect('profile-create')

        albums = Album.objects.filter(owner=profile)
        return self.render_to_response({'albums': albums, 'profile_exists': True})

templates/album-add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="/static/css/style.css" />
  </head>

  <body>
    <div id="box">
      <!-- Navigation Bar -->
      <header>
        <nav>
          <img src="/static/images/headphones.png" alt="headphones" />
          <a href="#">Home</a>
          <ul></ul>
          <ul>
            <!--Only for user with created profile-->
            <li><a href="#">Create Album</a></li>
            <li><a href="#">Profile</a></li>
          </ul>
        </nav>
      </header>
      <!-- End Navigation Bar -->

      <!-- Main Content -->
      <!--Create Page-->
      <section class="createPage">
        <form>
          <fieldset>
            <legend>Add Album</legend>
            <div class="container">
              <!-- Form for Adding Album -->
              <label for="name">Album Name:</label>
              <input id="name" type="text" placeholder="Album Name" required />

              <label for="artist">Artist:</label>
              <input id="artist" type="text" placeholder="Artist" required />

              <label for="genre">Genre:</label>
              <select id="genre" name="genre">
                <option value="1">-------</option>
                <option value="2">Pop Music</option>
                <option value="3">Jazz Music</option>
                <option value="4">R&B Music</option>
                <option value="5">Rock Music</option>
                <option value="6">Country Music</option>
                <option value="7">Dance Music</option>
                <option value="8">Hip Hop Music</option>
                <option value="9">Other</option>
              </select>

              <label for="description">Description:</label>
              <textarea id="description" placeholder="Description"></textarea>

              <label for="imgUrl">Image URL:</label>
              <input id="imgUrl" type="url" placeholder="Image URL" required />

              <label for="price">Price:</label>
              <input id="price" type="number" placeholder="Price" required />

              <!-- Button for Adding Album -->
              <button class="add-album" type="submit">Add New Album</button>
            </div>
          </fieldset>
        </form>
      </section>
      <!-- Footer -->
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
      <!-- End Footer -->
    </div>
  </body>
</html>

templates/albums/album-add.html
{% extends "base.html" %}

{% block main_content %}
    <section class="createPage">
        <form action="{% url "album-create" %}" method="post">
            <fieldset>
                <legend>Add Album</legend>
                <div class="container">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="add-album" type="submit">Add New Album</button>
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

templates/albums/album-delete.html
{% extends "base.html" %}

{% block main_content %}
    <section class="editPage">
        <form method="post">
            <fieldset>
                <legend>Delete Album</legend>
                <div class="container">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="delete-album" type="submit">Delete Album</button>
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

templates/albums/album-details.html
{% extends "base.html" %}

{% block main_content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="albumCover">
                <!-- Album Image -->
                <img src="{{ object.image_url }}" alt="{{ object.description }}"/>
            </div>

            <div class="albumInfo">
                <div class="albumText">
                    <!-- Album Info -->
                    <h1>Name: {{ object.album_name }}</h1>
                    <h3>Artist: {{ object.artist }}</h3>
                    <h4>Genre: {{ object.genre }}</h4>
                    <h4>Songs:
                        {% for song in album.songs.all %}
                            <a href="{% url "play-song" song.id %}">{{ song.song_name }}</a>
                            {% if not forloop.last %} | {% endif %}
                        {% endfor %}
                    </h4>
                    <h4>Price: {{ object.price }}</h4>
                    <p>Description: {{ object.description }}</p>
                </div>

                <div class="actionBtn">
                    <a href="{% url "album-edit" pk=object.pk %}" class="edit">Edit</a>
                    <a href="{% url "album-delete" pk=object.pk %}" class="remove">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/albums/album-edit.html
{% extends "base.html" %}

{% block main_content %}
      <section class="editPage">
        <form {% url "album-edit" pk=object.pk%} method="post">
          <fieldset>
            <legend>Edit Album</legend>
            <div class="container">
              {% csrf_token %}
                {{ form.as_p }}
              <button class="edit-album" type="submit">Edit Album</button>
            </div>
          </fieldset>
        </form>
      </section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static "/css/style.css" %}" />
  </head>

  <body>
    <div id="box">
      <!-- Navigation Bar -->
      <header>
        <nav>
          <img src="{% static '/images/headphones.png' %}" alt="headphones"/>
          <a href="{% url "index" %}" > Home</a>
          <ul></ul>
          <ul>
            {% if profile_exists %}
                <li><a href="{% url 'album-create' %}">Create Album</a></li>
                <li><a href="{% url "create-song" %}">Create Song</a></li>
                <li><a href="#">Profile</a></li>
            {% endif %}
          </ul>
        </nav>
      </header>
      <!-- End Navigation Bar -->
        {% block main_content %}
        {% endblock %}
        
        <!-- Footer -->
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
      <!-- End Footer -->
    </div>
  </body>
</html>

templates/profiles/profile-delete.html
{% extends "base.html" %}

{% block main_content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profileText">
                <!-- Delete Profile Form -->
                <h1>Are you sure you want to delete your profile?</h1>
                <form action="{% url 'profile-delete' %}" method="post">
                    {% csrf_token %}
                    <!-- Confirm Button -->
                    <button class="delete-profile" type="submit">Delete</button>
                </form>
                <!-- End Delete Profile Form -->
            </div>
        </div>
    </section>
{% endblock %}

templates/profiles/profile-details.html
{% extends "base.html" %}

{% block main_content %}
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profilePage">
            <img
              src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
              alt="Profile Image"
            />
          </div>

          <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ object.username }}</h1>
            <h1>Email: {{ object.email }}</h1>
            {% if object.age %}
                    <h1>Age: {{ object.age }}</h1>
                {% endif %}
            <h1>Albums: {{ object.album_set.count }}</h1>
          </div>

          <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url "profile-delete" %}" class="remove">Delete</a>
          </div>
        </div>
      </section>
{% endblock %}

templates/songs/create-song.html
{% extends "base.html" %}
{% block main_content %}

    <!--Create Page-->
    <section class="createPage">
        <form method="POST" action="{% url 'create-song' %}" enctype="multipart/form-data">
            <fieldset>
                <legend>Add Song</legend>
                <div class="container">
                    {{ form }}

                    <!-- File input for music file upload -->
                    <label for="music_file">Upload Music File:</label>
                    <input type="file" name="music_file" id="music_file" required>

                    {% csrf_token %}
                    <!-- Button for Song Album -->
                    <button class="add-song" type="submit">Add New Song</button>
                </div>
            </fieldset>
        </form>
    </section>

{% endblock %}

templates/songs/music-player.html
{% extends "base.html" %}

{% block main_content %}
<div>
    <div class="player">
        <div class="top">
            <button class="small">
                <div class="inner_button">
                    <!-- Your button SVG here -->
                </div>
            </button>
            <p class="indicator">PLAYING NOW</p>
            <button class="small">
                <div class="inner_button">
                    <!-- Your button SVG here -->
                </div>
            </button>
        </div>

        <div class="center">
            <!-- Album cover image -->
            <img class="album" src="{{ song.album.image_url }}">
        </div>

        <div class="song_details">
            <!-- Song details -->
            <div style="font-size: 20px;">{{ song.song_name }}</div>
            <div style="margin-top: 7px; font-size: 10px;">{{ song.song_name }}</div>
        </div>

        <div class="slider">
            <!-- Your existing slider elements -->
        </div>

        <div class="controls">
            <button class="big">
                <div class="inner_button_big">
                    <!-- Your back/previous button SVG here -->
                </div>
            </button>
            <button class="big_play_pause" onclick="togglePlayPause()">
                <div class="playpause playImg">
                    <!-- Your play SVG here -->
                </div>
                <div style="display: none;" class="playpause pauseImg">
                    <!-- Your pause SVG here -->
                </div>
            </button>
            <button class="big">
                <div class="inner_button_big">
                    <!-- Your next/forward button SVG here -->
                </div>
            </button>
        </div>

        <!-- Hidden audio player -->
        <audio id="audioPlayer">
            <source id="audioSource" src="{% url 'serve-song' song.id %}" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
    </div>
</div>

<script type="text/javascript">
function togglePlayPause() {
    let audioPlayer = document.getElementById('audioPlayer');
    let pauseImg = document.querySelector('.pauseImg');
    let playImg = document.querySelector('.playImg');

    if (audioPlayer.paused || audioPlayer.ended) {
        audioPlayer.play();
        pauseImg.style.display = 'inline-block';
        playImg.style.display = 'none';
    } else {
        audioPlayer.pause();
        pauseImg.style.display = 'none';
        playImg.style.display = 'inline-block';
    }
}
</script>

{% endblock %}

templates/web/home-no-profile.html
{% extends "base.html" %}

{% load static %}

{% block main_content %}
    
      <div class="container-inline">
        <section id="welcomePage">
          <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
          </div>
          <div class="music-img">
            <img src="{% static '/images/musicIcons.webp' %}" alt="music-icon"/>
          </div>
        </section>
          
        <section id="registerPage">
          <form method="post">
            <fieldset>
              <legend>Profile</legend>
              {{ form.as_p }}
                {% csrf_token %}
              <button type="submit" class="register">Enter</button>
            </fieldset>
          </form>
        </section>
      </div>
{% endblock %}
      

templates/web/home-with-profile.html
{% extends "base.html" %}

{% block main_content %}
    
      <section id="catalogPage">
          {% if not albums %}
            <p>No Albums in Catalog!</p>
          {% else %}
            <h1>All Albums</h1>
          {% endif %}
        
        {% for album in albums %}
        <div class="card-box">
          <img src="{{ album.image_url }}" alt="{{ album.description}}" />
          <div>
            <div class="text-center">
              <p class="name">Name: {{ album.album_name }}</p>
              <p class="artist">Artist: {{ album.artist }}</p>
              <p class="genre">Genre: {{ album.genre }}</p>
              <p class="price">Price: {{ album.price }}</p>
            </div>
            <div class="btn-group">
              <a href="{% url "album-details" pk=album.pk %}">Details</a>
            </div>
          </div>
        </div>
      {% endfor %}
       </section>
{% endblock %}